name: A workflow for my Hello World file
on: push
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Anthony"
  
  render:
    name: Screenshot Website
    runs-on: ubuntu-latest
    steps:
      - name: Screenshot Website Step
        uses: swinton/screenshot-website@v1.x
        with:
          source: https://cynthiasam.com/
          destination: screenshot.png

  healthcheck:
    runs-on: ubuntu-latest
    name: Check for status 200 and title text "Cynthia Sam"
    steps:
      - uses: actions/checkout@v2
      - id: test
        uses: johnlokerse/website-healthcheck@v2
        with:
          web-url: "https://cynthiasam.com"
          scan-for-text: "Cynthia Sam"


  lighthouse:
    runs-on: ubuntu-latest
    name: Lighthouse CI Action
    steps:
      - uses: actions/checkout@v2
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v8
        with:
          urls: |
            https://cynthiasam.com/
          budgetPath: ./budget.json # test performance budgets
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
