name: A workflow for my Hello World file
on: push
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Anthony"
  
  render website:
    name: Screenshot Website
    runs-on: ubuntu-latest
    steps:
      - name: Screenshot Website Step
      - uses: swinton/screenshot-website@v1.x
        with:
          source: https://github.com/swinton/screenshot-website
          destination: screenshot.png
